spring.application.name=sectors-api

server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5400/sectors
spring.datasource.username=sectors
spring.datasource.password=pass

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.liquibase.change-log=classpath:db/db.xml

server.servlet.session.cookie.max-age=600

logging.level.org.springframework.web=DEBUG